name: CI
on: 
  pull_request:
  push:
    tags:
      - "*"

jobs:
  ci:
    name: Lint on Update

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

  typos:
    name: Detect typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run typos
        uses: crate-ci/typos@v1.18.2
